PictureMe/PictureMe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from portfolio.views import (
    RobotsView,
    aboutme,
    contacts,
    index,
    phototerm,
)

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("robots.txt", RobotsView.as_view()),
    path("", index, name="index"),
    path("aboutme/", aboutme, name="aboutme"),
    path("contacts/", contacts, name="contacts"),
    path("phototerm/", phototerm, name="phototerm"),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    path("", include("django_prometheus.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PictureMe/portfolio/urls.py
from django.urls import path

from portfolio.views import element_detail, photoreports, series

app_name = "portfolio"

urlpatterns = [
    path("series/", series, name="series"),
    path("series/<int:element_id>/", element_detail, name="series_element"),
    path("reports/", photoreports, name="reports"),
    path("reports/<int:element_id>/", element_detail, name="reports_element"),
]

PictureMe/portfolio/models.py
import os

from colorfield.fields import ColorField
from django.core.validators import validate_image_file_extension
from django.db import models


class Album(models.Model):
    choices = [("ser", "Серии фотографий"), ("rep", "Репортаж")]
    type = models.CharField(max_length=3, default="ser", choices=choices)
    image = models.ImageField(upload_to="screensaver/")
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    style_number = models.PositiveIntegerField(default=1)
    text_color = ColorField(default="#000000", help_text="Выберите цвет текста")
    grad_color = ColorField(
        format="rgba",
        default="rgba(35,59,52,0.7)",
        help_text="Цвет градиента в формате RGBA",
        null=True,
        blank=True,
    )

    def __str__(self):
        return "Альбом " + self.first_name + " " + self.last_name + f" ({self.type})"


class Element(models.Model):
    choices = [("ser", "Серии фотографий"), ("rep", "Репортаж")]
    type = models.CharField(max_length=3, default="ser", choices=choices)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    style_number = models.PositiveIntegerField(default=1)
    description = models.TextField(null=True, blank=True)
    album = models.ForeignKey(to=Album, on_delete=models.PROTECT)
    text_color = ColorField(default="#000000", help_text="Выберите цвет текста")

    def __str__(self):
        return "Элемент " + self.first_name + " " + self.last_name


class Image(models.Model):
    image = models.ImageField(
        upload_to="photo/", validators=[validate_image_file_extension]
    )
    parent_element = models.ForeignKey(
        Element, on_delete=models.CASCADE, related_name="images", null=True, blank=True
    )  # Add this

    def __str__(self):
        return f"Фото {self.id} ({os.path.basename(self.image.name)})"


class Description(models.Model):
    """
    page='main' – текст на главной странице
    page='abme' – текст на странице обо мне
    """

    choices = [("main", "Главная страница"), ("abme", "Страница обо мне")]
    text = models.TextField()
    page = models.CharField(max_length=4, unique=True, choices=choices)
    main_photo = models.ImageField(upload_to="main/")

    def __str__(self):
        return "Описание " + (
            "главной страницы" if self.page == "main" else "страницы обо мне"
        )


class Order(models.Model):
    type_choices = [
        ("", "Выберите тему сообщения"),
        ("question", "Задать вопрос"),
        ("photo", "Заказать съёмку"),
        ("opinion", "Спросить совета"),
        ("other", "Другое"),
    ]
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=16, null=True, blank=True)
    email = models.EmailField()
    vk_url = models.CharField(max_length=30, null=True, blank=True)
    is_vk_answer = models.BooleanField(null=True, blank=True, default=False)
    message = models.TextField()
    purpose = models.CharField(max_length=20)
    get_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Заказ {self.id} с целью '{self.purpose}'"

PictureMe/portfolio/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView

from portfolio.form import OrderFrom
from portfolio.models import Album, Description, Element
from portfolio.vk_module import send_to_vk


class RobotsView(TemplateView):
    template_name = "photoUploading/robots.txt"
    content_type = "text/plain"


def index(request):
    context = {
        "description": Description.objects.filter(page="main")[0],
    }
    return render(request, "photoUploading/index.html", context)


def aboutme(request):
    context = {
        "description": Description.objects.filter(page="abme")[0],
    }
    return render(request, "photoUploading/aboutme.html", context)


def contacts(request):
    if request.method == "POST":
        form = OrderFrom(data=request.POST)
        if form.is_valid():
            form.instance.get_time = datetime.now()
            messages.success(request, "Ваше сообщение успешно отправлено!")
            form.instance.purpose = form.get_purpose_label()
            form.save()
            send_to_vk(str(form))
            return JsonResponse(
                {"status": "success", "message": "Ваше сообщение успешно отправлено!"}
            )
        else:
            return JsonResponse({"status": "error", "errors": form.errors}, status=400)
    else:
        form = OrderFrom()
    context = {"form": form}
    return render(request, "photoUploading/contacts.html", context=context)


def series(request):
    context = {
        "serie_els": Album.objects.filter(type="ser"),
    }
    return render(request, "photoUploading/series.html", context=context)


def phototerm(request):
    return render(request, "photoUploading/phototerm.html")


def photoreports(request):
    context = {
        "serie_els": Album.objects.filter(type="rep"),
    }
    return render(request, "photoUploading/photoreports.html", context=context)


def element_detail(request, element_id):
    element = Element.objects.filter(album=element_id)[0]
    return render(request, "photoUploading/element.html", {"element": element})


def is_admin(user):
    return user.is_authenticated and user.is_staff


@user_passes_test(is_admin)
def admin_dashboard(request):
    return render(request, "admin_dashboard.html")


def admin_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("admin_dashboard")
    return render(request, "templates/admin/login.html")

PictureMe/portfolio/templates/photoUploading/aboutme.html
{% extends 'photoUploading/base.html' %}
{%  load static %}
{% block title %}
  <title>Комолов Тимур – Обо мне</title>
  {% endblock %} title %}
{% block description %}
<meta name="description" content="Портфолио фотографа Тимура Комолова. Страница о фотографе.">
{% endblock %} description %}
{% block css %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="preload" href="{% static 'styles/aboutme.css' %}" as="style"
      onload="this.onload=null;this.rel='stylesheet'">
	<noscript>
  <link rel="stylesheet" href="{% static 'styles/aboutme.css' %}">
	</noscript>
{% endblock %}
{% block content %}
	<main class="main">
          <article>
            <div class="textbox">
              <h1>Обо мне</h1>
              <div class="itsme">
                <div class="D3__effect"
                     style="background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),
                     url({{ description.main_photo.url }}); background-size: 0, cover;">
                  <span class="descr-of-me">Это я с камерой ;)</span>
                </div>
              </div>
              <br>
              <p>{{ description.text }}</p>
              <p>На сайте школы у меня был интересный эффект с кастомным курсором, за которым двигались шарики. Я скопировал его на свой сайт, чтобы он не пропал бесследно. Для включения нажмите на кнопку. Но работать она будет только на компьютере, очевидно.</p>
              <button id="ball-turnoff">Включить кастомный курсор</button>
              <p>При желании, можете побаловаться с настройками шариков) Надо нажать на текст "настройка курсора". </p>
              <a href="#" id="toggle-cursor-settings" style="display:block; color: aqua; margin-top:15px;">настройки курсора↓</a>
				<div id="cursor-settings-container" style="display: none; margin-top: 10px;">
				  <label>Gravity: <input type="number" id="setting-gravity" step="any" value="30"></label><br>
				  <label>Bounce: <input type="number" id="setting-bounce" step="any" value="0.75"></label><br>
				  <label>Resistance: <input type="number" id="setting-resistance" step="any" value="10"></label><br>
				  <label>Mass: <input type="number" id="setting-mass" step="any" value="1"></label><br>
				  <label>SpringK: <input type="number" id="setting-springk" step="any" value="10"></label><br>
				  <button id="reset-cursor-defaults" style="margin-top:10px;">Восстановить значения по умолчанию</button>
				</div>
                </div>
              </article>
        </main>
{% endblock %}

PictureMe/portfolio/templates/photoUploading/admin.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static "admin/css/login.css" %}">
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content_title %}{% endblock %}

{% block nav-breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktranslate trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktranslate %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% translate 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <input type="submit" value="{% translate 'Log in' %}">
  </div>
</form>

</div>
{% endblock %}

PictureMe/portfolio/templates/photoUploading/base.html
{%  load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
  <title>Комолов Тимур</title>
  {% endblock %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" >
  {% block description %}
  <meta name="description" content="Портфолио фотографа Тимура Комолова.">
  {% endblock %}
  <link rel="icon" href="{% static 'images/cameraicon.png' %}" sizes="any">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Oswald&display=swap" rel="stylesheet">
  <meta name="yandex-verification" content="000c6cc5d2a6115a" />
  {% block css %}
  {% endblock %}
  </head>
  <body>
  <div id="cookie-popup">
        <p>На сайте используются файлы cookie для аналитики. Вы можете запретить передачу cookie для Яндекс.Метрики.</p>
        <button id="accept-cookies">Принять</button>
        <button id="decline-cookies">Запретить</button>
    </div>
    <div class="background">
        <header class="shapka">
            <div class="shapka__logo">
                <div class="image__logo">
                    <img src="{% static 'images/camera_large.png' %}" usemap="#Logo" alt="Логотип сайта" height="64px' %}">
                    <map name="Logo">
                        <area shape="rectangle" coords="0,0,100,100" href="{% url 'index' %}"></area>
                    </map>
                </div>
                <div class="logotext">
                Комолов Тимур
                </div>
            </div>
            <nav class="navbar">
              <input id="menu-toggle" type="checkbox" />
              <label class='menu-button-container' for="menu-toggle">
              <div class='menu-button'></div>
              <div class="menu-label">Меню</div>
              </label>
            <div class="shapka__blocks">
                <ul class="elements">
                    <li><a href="{% url 'index' %}">
                        <div class="shapka__blocks__item">
                            Главная
                        </div>
                    </a>
                    </li>
                    <li><a href="{% url "aboutme" %}">
                        <div class="shapka__blocks__item">
                            Обо мне
                        </div>
                    </a>
                    </li>
                    <li><a href="{% url "portfolio:series" %}">
                        <div class="shapka__blocks__item">
                            Серии фото
                        </div>
                    </a>
                    </li>
                    <li><a href="{% url "portfolio:reports" %}">
                        <div class="shapka__blocks__item">
                            Репортаж
                        </div>
                    </a>
                    </li>
                    <li><a href="{% url "phototerm" %}">
                        <div class="shapka__blocks__item">
                            Термины
                        </div>
                    </a>
                    </li>
                    <li><a  href="{% url "contacts" %}">
                        <div class="shapka__blocks__item">
                            Контакты
                        </div>
                    </a>
                    </li>
                </ul>

            </div>
        </nav>
        </header>
        <div id="dot0" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball0"></div>
		<div id="dot1" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball1"></div>
		<div id="dot2" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball2"></div>
		<div id="dot3" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball3"></div>
		<div id="dot4" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball4"></div>
		<div id="dot5" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball5"></div>
		<div id="dot6" class="dot" style="position:absolute; visibility:hidden; height:11px; width:11px;"><img src="{% static 'images/bullet.gif' %}" height="11" width="11" alt="ball6"></div>

        {% block content %}
        {% endblock %}
        {% block top-button %}
        	<aside id="upHere__container">
          <button onclick="topFunction()" id="upHere" title="Go to top"><img src="{% static 'images/up.svg' %}"></button>
      </aside>
      <script src="{% static 'js/button.js' %}"></script>
        {% endblock %}
        {% block scripts %}
        {% endblock %}
{#    <div class="flex-grow"></div>#}
        <footer class="dungeon">
            <div class="dungeon__text">
                <span>
                  <a href="https://vk.com/timik232">©Комолов Тимур</a>, 2022-<span id="currentYear"></span>
                </span>
                {% block social %}
                  <span class="media">
                    <span class="social-media-button vk-style" >
                    <a href="https://vk.com/timik232" class="circle" aria-label="Профиль VK">
                        <span class="logo"></span>
                        <span class="moving-gradient"></span>
                    </a>
                      <span class="glow"></span>
                    </span>
                    <span class="social-media-button telegram-style" aria-label="Страница ТГ">
                      <a href="https://t.me/ser13volk" class="circle">
                         <span class="logo"></span>
                        <span class="moving-gradient"></span>
                      </a>
                      <span class="glow"></span>
                    </span>
                    <span class="social-media-button github-style" >
                      <a href="https://www.github.com/timik232" class="circle" aria-label="Github профиль">
                        <span class="logo"></span>
                        <span class="moving-gradient"></span>
                      </a>
                      <span class="glow"></span>
                    </span>
                  </span>
                {% endblock %}
                {% block admin %}

                {% endblock %}
                  <span></span>
            </div>
        </footer>
    </div>
    <script>
      document.getElementById('currentYear').textContent = new Date().getFullYear();
    </script>
    <script src="{% static 'js/popup-cookie.js' %}" >
    </script>
    <!-- Яндекс.Метрика для пользователей, которые ранее уже согласились (если cookie установлено, popup не появится) -->
    <noscript>
        <div>
            <img src="https://mc.yandex.ru/watch/100105752" style="position:absolute; left:-9999px;" alt="" />
        </div>
    </noscript>
    <script src="{% static 'js/custom_cursor.js' %}"></script>
  </body>
  </html>

PictureMe/portfolio/templates/photoUploading/contacts.html
{% extends 'photoUploading/base.html' %}
{% load static %}
{% block title %}
  <title>Комолов Тимур – Контакты</title>
  {% endblock %} title %}
{% block description %}
<meta name="description" content="Портфолио фотографа Тимура Комолова. Страница с контактами">
{% endblock %} description %}
{% block css %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="preload" href="{% static 'styles/contacts.css' %}" as="style"
      onload="this.onload=null;this.rel='stylesheet'">
	<noscript>
  <link rel="stylesheet" href="{% static 'styles/contacts.css' %}">
	</noscript>
{% endblock %}
{% block content %}
    <main class="main__contact">
        <div class="textbox">
            <div class="text__contact">
                <article class="contact__text">
                    <h1>Контакты</h1>
                    <button id="turnoff">Выключить эффекты</button>
                    <br>
                    <ul>
                        <div class="grid__input grid__input_media ">
                            <div>
                                <li>
                                    <a href="https://vk.com/timik232">Мой ВК:</a>
                                </li>
                                <div class="social-media-button vk-style">
                                    <a href="https://vk.com/timik232" class="circle" aria-label="Профиль VK">
                                        <div class="logo"></div>
                                        <div class="moving-gradient"></div>
                                    </a>
                                    <div class="glow"></div>
                                </div>
                            </div>
                            <div>
                                <li><a href="https://www.youtube.com/@user-vl4ux2sr7l">Мой YouTube:</a></li>
                                <div class="social-media-button youtube-style">
                                    <a href="https://www.youtube.com/@user-vl4ux2sr7l" class="circle" aria-label="Youtube канал">
                                        <div class="logo"></div>
                                        <div class="moving-gradient"></div>
                                    </a>
                                    <div class="glow"></div>
                                </div>
                            </div>
                            <div>
                                <li><a href="https://t.me/ser13volk">Телеграмм:</a>
                                <li>
                                    <div class="social-media-button telegram-style">
                                        <a href="https://t.me/ser13volk" class="circle" aria-label="Страница в ТГ">
                                            <div class="logo"></div>
                                            <div class="moving-gradient"></div>
                                        </a>
                                        <div class="glow"></div>
                                    </div>
                            </div>
                            <div>
                                <li><a href="https://www.github.com/timik232">Мой гитхаб:</a></li>
                                <div class="social-media-button github-style">
                                    <a href="https://www.github.com/timik232" class="circle" aria-label="Ссылка на GitHub">
                                        <div class="logo"></div>
                                        <div class="moving-gradient"></div>
                                    </a>
                                    <div class="glow"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <li>Моя почта: <a href="mailto:komolov.timurka@mail.ru">komolov.timurka@mail.ru</a></li>
                    </ul>
                    <br>
                    <div class="color"></div>
                    <div class="color"></div>
                    <div class="color"></div>
                    <div class="box">
                        <div class="square" style="--i:0;"></div>
                        <div class="square" style="--i:1;"></div>
                        <div class="square" style="--i:2;"></div>
                        <div class="square" style="--i:3;"></div>
                        <div class="square" style="--i:4;"></div>
                        <div class="square" style="--i:5;"></div>
                    </div>
                    <form action="" method="post" class="sendMessage">
                        {% csrf_token %}
                        <fieldset id="send">
                            <legend id="legsend"><h2>Отправить письмо</h2></legend>
                            <div class="grid__input">
                          <span class="grid__column">
                            <label for="{{ form.name.id_for_label }}">Имя и фамилия</label>
                          <div class="inp">{{ form.name }}</div>
                         <label for="{{ form.email.id_for_label }}">Email</label>
                          <div class="inp">{{ form.email }}</div>
                        </span>
                                <span class="grid__column">
                            <label for="{{ form.phone_number.id_for_label }}">Номер телефона(необязательно):</label>
                          <div class="inp">{{ form.phone_number }}</div>
                          <label for="{{ form.vk_url.id_for_label }}">Ссылка на вк (необязательно):</label>
                          <div class="inp">{{ form.vk_url }}</div>
                        </span>
                            </div>
                            <label for="{{ form.is_vk_answer.id_for_label }}">Отвечать в вк? </label>
                            {{ form.is_vk_answer }}<br>
                            <label for="{{ form.message.id_for_label }}">Сообщение</label>
                            <div class="inp">{{ form.message }}</div>
                            <label for="{{ form.purpose1.id_for_label }}">Тема сообщения</label><br>
                            {{ form.purpose1 }}
                            {#                          <select name="topic" id="topic" autofocus required>#}
                            {#                            <option value="">Выберите тему сообщения</option>#}
                            {#                            <option value="question">Задать вопрос</option>#}
                            {#                            <option value="photo">Заказать съёмку</option>#}
                            {#                            <option value="opinion">Спросить совета</option>#}
                            {#                            <option value="other">Другое</option>#}
                            {#                          </select>#}
                            <br>
                            <button type="submit" id="submit" value="Отправить">Отправить</button>
                        </fieldset>
                    </form>
                </article>
            </div>
        </div>
    </main>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/submit.js' %}?v=2.0"></script>
    {% if messages %}
        {#    <script>#}
        {#        alert("{{ messages }}");#}
        {#    </script>#}
    {% endif %}
{% endblock %}
{% block top-button %}
{% endblock %}
{% block social %}
{% endblock %}

PictureMe/portfolio/templates/photoUploading/photoreports.html
{% extends 'photoUploading/base.html' %}
{%  load static %}
{% block title %}
  <title>Комолов Тимур – Репортаж</title>
  {% endblock %} title %}
{% block description %}
<meta name="description" content="Портфолио фотографа Тимура Комолова. Страница с репортажем.">
{% endblock %} description %}
{% block css %}
	<link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/series.css' %}">
    <link rel="preload" href="{% static 'styles/photoreports.css' %}" as="style"
      onload="this.onload=null;this.rel='stylesheet'">
	<noscript>
  <link rel="stylesheet" href="{% static 'styles/photoreports.css' %}">
	</noscript>
{% endblock %}
{% block content %}
	<main class="main">
          <article>
          <div class="reports">
            <ul>
                {% for el in serie_els %}
                    <li><a href="{% url 'portfolio:reports_element' el.id  %}">
                         {% if el.text_color and el.grad_color %}
                    <div class="hover-text-one" style="--textcol: {{ el.text_color }}; --grad: {{ el.grad_color }};">
                        {% else %}
                    <div class="hover-text-one report{{ el.style_number }}">
                    {% endif %}

                    <figure class="effect-text-two">
                      <img src="{{ el.image.url }}" width=460px alt="{{el.image.url}}">

                        <figcaption>
        {#                    <p>Репетиции <span> бала</span></p>#}
                    <p>{{ el.first_name }} <span> {{ el.last_name }}</span></p>
                        </figcaption>
                    </figure>
                  </div>
                  </a></li>
                {% endfor %}
            </ul>
          </div>
          </article>
        </main>
{% endblock %}

PictureMe/portfolio/templates/photoUploading/series.html
{% extends 'photoUploading/base.html' %}
{%  load static %}
{% block css %}
	<link rel="stylesheet" href="{% static 'styles/main.css' %}">
	<link rel="preload" href="{% static 'styles/series.css' %}" as="style"
      onload="this.onload=null;this.rel='stylesheet'">
	<noscript>
  <link rel="stylesheet" href="{% static 'styles/series.css' %}">
	</noscript>
{% endblock %}
{% block content %}
	<main class="main">
          <article>
            <div class="series">
              <ul>
                  {% for el in serie_els %}
                      <li><a href="{% url 'portfolio:series_element' el.id  %}">
                    {% if el.text_color and el.grad_color %}
                    <div class="hover-text-one" style="--textcol: {{ el.text_color }}; --grad: {{ el.grad_color }};">
                        {% else %}
                          <div class="hover-text-one serie{{ el.style_number }}">
                    {% endif %}
                      <figure class="effect-text-two">
                        <img src="{{ el.image.url }}" width=460px alt="{{el.image.url}}">
                          <figcaption>
                        <p>{{ el.first_name }} <span> {{ el.last_name }}</span></p>
                          </figcaption>
                      </figure>
                    </div>
                    </a></li>
                  {% endfor %}
            </ul>
            </div>
          </article>
        </main>
{% endblock %}